### ISSUE TITLE
Slooow TCI URL retrieval

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/s2_tci#1]
The core part of this package is to retrieve the TCI URLs for specified products on SciHub.

https://github.com/DHI-GRAS/s2_tci/blob/master/s2_tci/find.py

But this takes **ages**. Can we speed it up somehow?

NB: An obstacle to just throwing concurrency at it is that you are only allowed two parallel downloads per user account.

**Comment by j08lue** [comment]
Here is some minimal example to work on: https://gist.github.com/j08lue/b8709dbf23fa4606ffd06efb6c284b9d

**Comment by dionhaefner** [comment]
I experimented a bit with the API, but I don't see a way to get this to perform better. Seems like the server latency is quite high when requesting the different bands in the granule file. To make it feel more reactive, you could yield the links one-by-one and start downloading immediately (that way you also notice errors earlier).

**Comment by j08lue** [comment]
Thanks for looking into this, @dionhaefner.
