### ISSUE TITLE
Command samples

### ISSUE THREAD

**Issue by webmap2015** [DHI-GRAS/s2_tci#4]
Hi,
I can't find command samples for downloading.
Could you help ?

Thanks.

**Comment by j08lue** [comment]
Thanks for the interest @webmap2015. I have not run this code in years, no idea whether it still works. But please have a look at the `chain` module and the `download_tci` function which ties everything together https://github.com/DHI-GRAS/s2-tci/blob/c656d5f224601295d3b344fab4c97653e1ddee8f/s2_tci/chain.py#L18
